version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: plug
    versions:
    - 1.11.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
